//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFilms_.NET_Framework_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilmsRating
    {
        public string login { get; set; }
        public int film_id { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<decimal> rating { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual UserFilmStatus UserFilmStatus { get; set; }
        public virtual User User { get; set; }
    }
}
