//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFilms_.NET_Framework_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilmsRatingsCount
    {
        public int film_id { get; set; }
        public Nullable<int> all_ratings_count { get; set; }
        public Nullable<int> C1_ratings_count { get; set; }
        public Nullable<int> C2_ratings_count { get; set; }
        public Nullable<int> C3_ratings_count { get; set; }
        public Nullable<int> C4_ratings_count { get; set; }
        public Nullable<int> C5_ratings_count { get; set; }
    }
}
