//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFilms_.NET_Framework_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilmsCrew
    {
        public int film_id { get; set; }
        public int crew_id { get; set; }
        public int department_id { get; set; }
        public string job { get; set; }
    
        public virtual Crew Crew { get; set; }
        public virtual Department Department { get; set; }
        public virtual Film Film { get; set; }
    }
}
